In [4]:
import numpy as np

In [6]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket indexing and selection

In [7]:
arr[0]

0

In [8]:
arr[5]

5

In [9]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays give the capability to broadcast i.e. set a value of a given range

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Indexing 2-D arrays/matrices

In [12]:
arr2D = np.array([[1,2,3],[3,4,5],[6,7,8]])
arr2D

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
arr2D[1]

array([3, 4, 5])

In [15]:
arr2D[2][1]

7

### Selection or Conditional Selection

Numpy gives capability of creating boolean arrays by giving a condition and selecting a part of array

In [19]:
arr = np.arange(1,11)

In [20]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [22]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])