<img src='https://numpy.org/_static/numpy_logo.png'>
NumPy is the fundamental package for scientific computing with Python. 
It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

Its the library which is used extensively for linear algebra purposes.

## Using numpy

In [1]:
!pip install numpy

## Numpy arrays

Basic building blocks of numpy

2 type of arrays:
* vectors - 1-d array
* matrix - 2-d

In [4]:
import numpy as np # import <package_name> as <alias_name>

In [5]:
# creating numpy arrays from python list
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in methods

#### arange

Returns evenly spaced values in a given interval

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate array of zeros and ones

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace
Returns evenly spaced numbers over a specified interval

In [20]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## Random
Numpy has a lot of ways to create random numbers

### rand
Creates an array od given shape and populate it with random samples of uniform distribution over 0,1.

In [24]:
np.random.rand(2)

array([0.47622831, 0.84556012])

In [26]:
np.random.rand(5,5)

array([[0.60816565, 0.8816641 , 0.92948747, 0.96492749, 0.04776406],
       [0.54579881, 0.09346031, 0.36472637, 0.58750156, 0.56610104],
       [0.52575428, 0.47062945, 0.45775668, 0.88964341, 0.05530207],
       [0.99196061, 0.30867595, 0.49380303, 0.65892781, 0.28391602],
       [0.64367059, 0.97747629, 0.87888251, 0.87158492, 0.00836374]])

### randn
Returns a sample of standard normal distribution. Unlike rand which give uniform distribution.

In [27]:
np.random.randn(2)

array([ 1.06099079, -0.66305225])

In [28]:
np.random.randn(5,5)

array([[-1.90396719, -1.20322485,  0.39073159, -1.50842271,  0.41013803],
       [-0.08694717, -0.82303618, -0.17110077,  0.24999942, -0.589349  ],
       [ 1.24040312,  0.37659476,  0.7152844 , -0.69727979,  1.45213169],
       [ 0.11677157,  1.27149946, -0.33959745, -0.39312712,  1.02461132],
       [-1.27483517,  1.04546346,  1.96478245,  0.85919043,  0.11680257]])

## randint
Returns the random integers from low (included) to high (excluded)

In [29]:
np.random.randint(1,100)

40

In [30]:
np.random.randint(1,100,4)

array([13, 77,  9, 15])

## Array attributes

In [31]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr

array([10,  0, 33, 37, 21, 42, 12, 15,  4, 43])

In [42]:
ranarr.shape

(10,)

In [45]:
x = ranarr.reshape(5,2)
x

array([[10,  0],
       [33, 37],
       [21, 42],
       [12, 15],
       [ 4, 43]])

In [46]:
x.shape

(5, 2)

## Reshape

Returns an array containting the same data in the given shape

In [34]:
arr.shape

(25,)

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, and argmin

In [36]:
ranarr

array([10,  0, 33, 37, 21, 42, 12, 15,  4, 43])

In [37]:
ranarr.max()

43

In [38]:
ranarr.argmax()

9

In [39]:
ranarr.min()

0

In [40]:
ranarr.argmin()

1

In [41]:
ranarr.shape

(10,)

## Great Job !!