In [1]:
distance = [30,40,10,20,50]
time = [2,1.9,0.3,1,10]

In [2]:
speed = distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [3]:
import numpy as np

In [4]:
np_dist = np.array(distance)
np_time = np.array(time)

In [5]:
speed = np_dist/np_time

In [6]:
speed

array([15.        , 21.05263158, 33.33333333, 20.        ,  5.        ])

In [7]:
import numpy

In [8]:
one_darray = np.array([1,2,3,4,5])

In [9]:
print(one_darray)

[1 2 3 4 5]


In [10]:
two_darray = np.array([[1,2,3],[4,5,6]])

In [11]:
print(two_darray)

[[1 2 3]
 [4 5 6]]


In [12]:
three_darray = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [13]:
print(three_darray)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
one_darray.ndim

1

In [15]:
two_darray.ndim

2

In [16]:
three_darray.ndim

3

In [17]:
one_darray.shape

(5,)

In [18]:
two_darray.shape

(2, 3)

In [19]:
three_darray.shape

(2, 2, 2)

In [20]:
one_darray.size

5

In [21]:
two_darray.size

6

In [22]:
three_darray.size

8

In [23]:
one_darray.dtype

dtype('int64')

In [24]:
two_darray.dtype

dtype('int64')

In [25]:
three_darray.dtype

dtype('int64')

In [27]:
one_darray.astype('str')

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [28]:
one_darray.astype('float')

array([1., 2., 3., 4., 5.])

In [34]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,9,4,5])

In [35]:
a & b

array([1, 2, 1, 4, 5])

In [36]:
a | b

array([ 1,  2, 11,  4,  5])

In [32]:
a ~ b

SyntaxError: invalid syntax (<ipython-input-32-64e8a359a75e>, line 1)

In [37]:
~a

array([-2, -3, -4, -5, -6])

In [38]:
cycle_data = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [39]:
cycle_data[0]

array([1, 2, 3, 4, 5])

In [40]:
cycle_data[1]

array([ 6,  7,  8,  9, 10])

In [41]:
cycle_data[0][0]

1

In [42]:
cycle_data[1][2]

8

In [43]:
cycle_data[0:1]

array([[1, 2, 3, 4, 5]])

In [44]:
cycle_data[:0]

array([], shape=(0, 5), dtype=int64)

In [45]:
cycle_data[:1]

array([[1, 2, 3, 4, 5]])

In [46]:
cycle_data[::1]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [49]:
cycle_data[:,0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [50]:
cycle_data[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
cycle_data[:,0]

array([1, 6])

In [53]:
cycle_data[:,0:2] #slicing according to columns

array([[1, 2],
       [6, 7]])

In [56]:
cycle_data[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [58]:
for row in cycle_data:
    for item in row:
        print(item)

1
2
3
4
5
6
7
8
9
10


In [59]:
for row in cycle_data:
    print(row)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [60]:
test_score = np.array

In [61]:
test_score = np.array([[83, 71, 57, 63],[54, 68, 81, 45]])

In [62]:
passing_score = test_score > 60

In [63]:
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [64]:
test_score[passing_score]

array([83, 71, 63, 68, 81])

In [65]:
one_darray

array([1, 2, 3, 4, 5])

In [66]:
a = one_darray

In [67]:
a

array([1, 2, 3, 4, 5])

In [68]:
a[0] = 10

In [69]:
a

array([10,  2,  3,  4,  5])

In [70]:
one_darray

array([10,  2,  3,  4,  5])

In [71]:
a is one_darray

True

In [72]:
b = one_darray.view()

In [73]:
b

array([10,  2,  3,  4,  5])

In [74]:
one_darray

array([10,  2,  3,  4,  5])

In [75]:
b[0] = 1

In [76]:
b

array([1, 2, 3, 4, 5])

In [77]:
one_darray

array([1, 2, 3, 4, 5])

In [78]:
b is one_darray

False

In [79]:
c = one_darray.copy()

In [80]:
c

array([1, 2, 3, 4, 5])

In [81]:
one_darray

array([1, 2, 3, 4, 5])

In [82]:
c[0] = -1

In [83]:
c

array([-1,  2,  3,  4,  5])

In [84]:
one_darray

array([1, 2, 3, 4, 5])

In [85]:
np.sqrt([1,2,3,4,5])

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [86]:
np.floor([3.2,4.5,6.9,2.7])

array([3., 4., 6., 2.])

In [87]:
np.exp([0,1,2,3,4])

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [88]:
np.sin(np.pi/2)

1.0

In [90]:
np.ceil([3.2,4.5,6.9,2.7])

array([4., 5., 7., 3.])

In [91]:
np.cos(0)

1.0

In [94]:
np.sin([0,1,2,3,4,5])

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [96]:
sin = np.sin

In [97]:
sin(0)

0.0

In [98]:
cycle_data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [99]:
cycle_data.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
cycle_data.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [101]:
cycle_data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [102]:
cycle_data.resize(5,2)

In [103]:
cycle_data

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [104]:
cycle_data.shape

(5, 2)

In [105]:
len(cycle_data)

5

In [106]:
cycle_data.size

10

In [107]:
np.hsplit(cycle_data, 2)

[array([[1],
        [3],
        [5],
        [7],
        [9]]), array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]])]

In [108]:
np.hstack((np.array([1,2,3,4]),np.array([5,6,7,8])))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [109]:
np.stack((np.array([1,2,3,4]),np.array([5,6,7,8])))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [116]:
a = np.array([2,4,6,8])
b = np.array([1,3,5,7])

In [115]:
a + b

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [120]:
a - 2

array([0, 2, 4, 6])

In [121]:
two_darray

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
two_darray.transpose()

array([[1, 3],
       [2, 4]])

In [123]:
two_darray = np.array([[1,2],[3,4]])
np.linalg.inv(two_darray)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [124]:
np.trace(two_darray)

5

In [ ]:
np.trace